In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
elec = pd.read_csv('countypres_2000-2020.csv')
elec

,year,state,state_po,county_name,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
0,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,AL GORE,DEMOCRAT,4942,17208,20220315,TOTAL
1,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,GEORGE W. BUSH,REPUBLICAN,11993,17208,20220315,TOTAL
2,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,RALPH NADER,GREEN,160,17208,20220315,TOTAL
3,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,OTHER,OTHER,113,17208,20220315,TOTAL
4,2000,ALABAMA,AL,BALDWIN,1003.0,US PRESIDENT,AL GORE,DEMOCRAT,13997,56480,20220315,TOTAL
...,...,...,...,...,...,...,...,...,...,...,...,...
72612,2020,WYOMING,WY,WASHAKIE,56043.0,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,3245,4032,20220315,TOTAL
72613,2020,WYOMING,WY,WESTON,56045.0,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,360,3560,20220315,TOTAL
72614,2020,WYOMING,WY,WESTON,56045.0,US PRESIDENT,JO JORGENSEN,LIBERTARIAN,46,3560,20220315,TOTAL
72615,2020,WYOMING,WY,WESTON,56045.0,US PRESIDENT,OTHER,OTHER,47,3560,20220315,TOTAL
72616,2020,WYOMING,WY,WESTON,56045.0,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,3107,3560,20220315,TOTAL

In [30]:
elec = elec[elec['year']==2016]
elec = elec[(elec['party']=='DEMOCRAT') | (elec['party']=='REPUBLICAN')]
# elec[(elec['county_fips']>2000) & (elec['county_fips']<3000)]

,year,state,state_po,county_name,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode,% votes
50401,2016,ALASKA,AK,DISTRICT 1,2001.0,US PRESIDENT,HILLARY CLINTON,DEMOCRAT,2573,6638,20220315,TOTAL,0.387617
50402,2016,ALASKA,AK,DISTRICT 1,2001.0,US PRESIDENT,DONALD TRUMP,REPUBLICAN,3180,6638,20220315,TOTAL,0.479060
50404,2016,ALASKA,AK,DISTRICT 2,2002.0,US PRESIDENT,HILLARY CLINTON,DEMOCRAT,1585,5492,20220315,TOTAL,0.288602
50405,2016,ALASKA,AK,DISTRICT 2,2002.0,US PRESIDENT,DONALD TRUMP,REPUBLICAN,3188,5492,20220315,TOTAL,0.580481
50407,2016,ALASKA,AK,DISTRICT 3,2003.0,US PRESIDENT,HILLARY CLINTON,DEMOCRAT,1241,7613,20220315,TOTAL,0.163011
...,...,...,...,...,...,...,...,...,...,...,...,...,...
50516,2016,ALASKA,AK,DISTRICT 39,2039.0,US PRESIDENT,DONALD TRUMP,REPUBLICAN,1405,5639,20220315,TOTAL,0.249158
50518,2016,ALASKA,AK,DISTRICT 40,2040.0,US PRESIDENT,HILLARY CLINTON,DEMOCRAT,2338,4610,20220315,TOTAL,0.507158
50519,2016,ALASKA,AK,DISTRICT 40,2040.0,US PRESIDENT,DONALD TRUMP,REPUBLICAN,1377,4610,20220315,TOTAL,0.298698
50521,2016,ALASKA,AK,DISTRICT 99,2099.0,US PRESIDENT,HILLARY CLINTON,DEMOCRAT,274,342,20220315,TOTAL,0.801170
50522,2016,ALASKA,AK,DISTRICT 99,2099.0,US PRESIDENT,DONALD TRUMP,REPUBLICAN,40,342,20220315,TOTAL,0.116959

In [14]:
elec['% votes'] = elec['candidatevotes']/elec['totalvotes']
elec_new = pd.pivot_table(elec, values='% votes', index=['county_fips'],columns=['party'])
elec_new

party        DEMOCRAT  REPUBLICAN
county_fips
1001.0       0.237697    0.727666
1003.0       0.193856    0.765457
1005.0       0.465278    0.520967
1007.0       0.212496    0.764032
1009.0       0.084258    0.893348
...               ...         ...
56037.0      0.188616    0.709515
56039.0      0.579235    0.310525
56041.0      0.141913    0.726564
56043.0      0.139486    0.763241
56045.0      0.084799    0.860182

[3154 rows x 2 columns]

In [21]:
elec_new.index = elec_new.index.astype(int)

In [26]:
elec_new.reset_index().to_csv('election_data.csv',index=False)